Repository eslint/js, pull requests merged in 2018-03, with the labels that each got.

#369 Upgrade: acorn 5.5.0
  package.json
  tests/fixtures/ecma-version/6/regexUFlag/regex-u-invalid-extended-escape.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/invalid-group.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/invalid-group.src.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/invalid-unterminated-group.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/invalid-unterminated-group.src.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-1.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-1.src.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-2.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-2.src.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-1.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-1.src.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-2.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-2.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-1.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-1.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-2.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-2.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-3.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-3.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-4.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-backreference-4.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-1.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-1.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-2.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-2.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-3.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/invalid-group-name-3.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-1.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-1.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-2.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-2.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-3.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-backreference-3.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-group.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-group.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-unicode-name-1.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-unicode-name-1.src.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-unicode-name-2.result.js
  tests/fixtures/ecma-version/9/regexp-named-group/valid-unicode-name-2.src.js
  tests/fixtures/ecma-version/9/regexp-s-flag/s-flag.result.js
  tests/fixtures/ecma-version/9/regexp-s-flag/s-flag.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-1.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-1.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-2.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-2.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-3.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-3.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-4.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/invalid-property-4.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-negative-1.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-negative-1.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-negative-2.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-negative-2.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-positive-1.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-positive-1.src.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-positive-2.result.js
  tests/fixtures/ecma-version/9/regexp-unicode-property-escape/valid-positive-2.src.js
Labels: triage

#370 Upgrade: acorn 5.5.1
  package.json
  tests/fixtures/ecma-version/6/templateStrings/octal-literal.result.js
Labels: triage

#371 Breaking: require Node.js 6+, upgrade acorn-jsx@4.1.1 (fixes #345)
  .travis.yml
  package.json
  tests/fixtures/ecma-features/jsx/embedded-invalid-js-identifier.result.js
  tests/fixtures/ecma-features/jsx/embedded-tags.result.js
  tests/fixtures/ecma-features/jsx/multiple-blank-spaces.result.js
  tests/fixtures/ecma-features/jsx/namespaced-attribute-and-value-inserted.result.js
  tests/fixtures/ecma-features/jsx/template-strings-in-jsx-complex.result.js
  tests/fixtures/ecma-features/jsx/test-content.result.js
  tests/fixtures/ecma-version/6/regexUFlag/regex-u-simple.result.js
  tests/fixtures/ecma-version/6/regexYFlag/regexp-y-simple.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-1.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-negative-2.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-1.result.js
  tests/fixtures/ecma-version/9/regexp-lookbehind-assertion/valid-positive-2.result.js
  tests/fixtures/ecma-version/9/regexp-s-flag/s-flag.result.js
Labels: triage

#374 Breaking: remove experimentalObjectRestSpread option
  README.md
  espree.js
  lib/ast-node-types.js
  lib/features.js
  lib/visitor-keys.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/arg-spread.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/arg-spread.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/destructuring-assign-mirror.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/destructuring-assign-mirror.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/invalid-rest-trailing-comma.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/invalid-rest-trailing-comma.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/invalid-rest.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/invalid-rest.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/object-rest.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/object-rest.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/property-spread.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/property-spread.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-method-args.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-method-args.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-methods.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-methods.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-properties.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/shorthand-properties.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/single-spread.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/single-spread.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/spread-trailing-comma.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/spread-trailing-comma.src.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/two-spread.result.js
  tests/fixtures/ecma-features/experimentalObjectRestSpread/two-spread.src.js
  tests/lib/ecma-features.js
Labels: accepted, breaking, enhancement

#375 Build: fix typos in package.json release scripts
  package.json
Labels: accepted, bug

#376 Upgrade: eslint-release to v0.11.1
  package.json
Labels: triage
