Repository eslint/js, pull requests merged in 2018-10, with the labels that each got.

#389 VisitorKeys depend on eslint-visitor-keys
  espree.js
  lib/visitor-keys.js
  package.json
Labels: triage

#392 Upgrade: eslint-release@1.0.0
  .gitignore
  package.json
Labels: build, chore

#391 Upgrade: acorn 6, acorn-jsx 5, and istanbul
  .eslintrc
  .gitignore
  .nycrc
  Makefile.js
  espree.js
  lib/espree.js
  package.json
Labels: accepted, chore
