Repository eslint/js, pull requests merged in 2019-08, with the labels that each got.

#415 Update: support bigint and dynamic import
  .eslintignore
  .travis.yml
  espree.js
  lib/espree.js
  package.json
  tests/fixtures/ecma-version/11/bigint/binary.result.js
  tests/fixtures/ecma-version/11/bigint/binary.src.js
  tests/fixtures/ecma-version/11/bigint/decimal.result.js
  tests/fixtures/ecma-version/11/bigint/decimal.src.js
  tests/fixtures/ecma-version/11/bigint/hex.result.js
  tests/fixtures/ecma-version/11/bigint/hex.src.js
  tests/fixtures/ecma-version/11/bigint/invalid-float.result.js
  tests/fixtures/ecma-version/11/bigint/invalid-float.src.js
  tests/fixtures/ecma-version/11/bigint/octal.result.js
  tests/fixtures/ecma-version/11/bigint/octal.src.js
  tests/fixtures/ecma-version/11/dynamic-import/basic.result.js
  tests/fixtures/ecma-version/11/dynamic-import/basic.src.js
  tests/fixtures/ecma-version/11/dynamic-import/first-of-statement.result.js
  tests/fixtures/ecma-version/11/dynamic-import/first-of-statement.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-import-prop.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-import-prop.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-multi-sources.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-multi-sources.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-new-import.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-new-import.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-no-source.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-no-source.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-only-import.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-only-import.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-trailing-comma.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-trailing-comma.src.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-wrap-import.result.js
  tests/fixtures/ecma-version/11/dynamic-import/invalid-wrap-import.src.js
  tests/fixtures/ecma-version/11/dynamic-import/new-import.result.js
  tests/fixtures/ecma-version/11/dynamic-import/new-import.src.js
  tests/fixtures/ecma-version/11/dynamic-import/with-assign.result.js
  tests/fixtures/ecma-version/11/dynamic-import/with-assign.src.js
  tests/fixtures/ecma-version/11/dynamic-import/with-sequence.result.js
  tests/fixtures/ecma-version/11/dynamic-import/with-sequence.src.js
  tests/fixtures/ecma-version/6/forOf/for-of-with-function-initializer.result.js
  tests/lib/tester.js
Labels: accepted, enhancement

#419 Fix: tokenize the latest right curly brace (fixes #403)
  lib/espree.js
  tests/lib/tokenize.js
Labels: accepted, bug

#421 Update: improve error messaging when validating ecmaVersion
  lib/espree.js
  tests/lib/ecma-version.js
Labels: enhancement

#422 Docs: update readme to mention ES2020
  README.md
Labels: triage
