Repository eslint/js, pull requests merged in 2021-11, with the labels that each got.

#518 feat: support class static blocks
  README.md
  package.json
Labels: accepted

#521 feat: support for private-in syntax
  package.json
  tests/fixtures/ecma-version/13/private-in/invalid-missing-private.result.js
  tests/fixtures/ecma-version/13/private-in/invalid-missing-private.src.js
  tests/fixtures/ecma-version/13/private-in/invalid-without-class.result.js
  tests/fixtures/ecma-version/13/private-in/invalid-without-class.src.js
  tests/fixtures/ecma-version/13/private-in/valid-private-in.result.js
  tests/fixtures/ecma-version/13/private-in/valid-private-in.src.js
Labels: enhancement, accepted

#520 feat: Add sourceType:commonjs support
  README.md
  lib/espree.js
  lib/options.js
  tests/lib/parse.js
Labels: enhancement

#523 docs: add private-in syntax
  README.md
Labels: accepted, documentation

#522 feat: add `allowReserved` for ES3
  README.md
  lib/options.js
  tests/lib/ecma-version.js
Labels: enhancement, accepted

#524 ci: use node `v16`
  .github/workflows/ci.yml
Labels: triage
