Repository eslint/js, pull requests merged in 2021-06, with the labels that each got.

#499 Breaking: Implement 'ecmaVersion: latest' (fixes #495)
  README.md
  lib/options.js
  tests/lib/ecma-version.js
  tests/lib/libraries.js
  tests/lib/options.js
  tests/lib/parse.js
  tests/lib/tokenize.js
Labels: breaking, enhancement

#502 Breaking: drop node v10/13/v15 (fixes #501)
  .github/workflows/ci.yml
  package.json
Labels: accepted, breaking

#506 Update: reset default ecmaVersion to 5
  README.md
  lib/options.js
  tests/lib/ecma-version.js
  tests/lib/options.js
  tests/lib/parse.js
  tests/lib/tokenize.js
Labels: accepted, enhancement

#505 Update: Support top-level await and regexp match indices
  README.md
  package.json
  tests/fixtures/ecma-version/13/modules/top-level-await/top-await.result.js
  tests/fixtures/ecma-version/13/modules/top-level-await/top-await.src.js
  tests/fixtures/ecma-version/13/regexp-match-indices/regexp-match-indices.result.js
  tests/fixtures/ecma-version/13/regexp-match-indices/regexp-match-indices.src.js
  tests/lib/conditional-regex-value.js
Labels: accepted, enhancement

#507 Upgrade: eslint-visitor-keys@3.0.0
  espree.js
  package.json
Labels: triage
