Repository eslint/js, pull requests merged in 2021-09, with the labels that each got.

#514 Fix: 0x2028 and 0x2029 in string literals should increment line number
  package.json
  tests/fixtures/ecma-version/10/json-superset/valid-2028.result.js
  tests/fixtures/ecma-version/10/json-superset/valid-2029.result.js
  tests/fixtures/ecma-version/6/newTarget/invalid-new-target.result.js
Labels: bug, dependency

#513 Breaking: Disallow reserved words in ES3
  lib/espree.js
  lib/options.js
  tests/lib/ecma-version.js
Labels: accepted, breaking

#515 Chore: add class static blocks tests
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-new-target.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-new-target.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-this.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-expr-this.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-close.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-close.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-derived.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-derived.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-open.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-lex-open.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-private.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-private.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-close.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-close.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-derived.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-derived.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-open.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-scope-var-open.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-sequence.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-sequence.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-statement-list-optional.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-statement-list-optional.src.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-super-property.result.js
  tests/fixtures/ecma-version/13/class-static-blocks/statements-class-static-init-super-property.src.js
Labels: triage
