Repository eslint/js, pull requests merged in 2021-04, with the labels that each got.

#479 Build: Update branch reference in CI
  .github/workflows/ci.yml
Labels: accepted, build

#478 Build: Update scripts for release (fixes #475)
  .github/workflows/ci.yml
  lib/version.js
  package.json
  rollup.config.js
  tools/update-version.js
Labels: accepted, build

#477 Docs: Update README with ESM instructions (fixes #474)
  README.md
  docs/README.md
Labels: accepted, documentation

#476 Chore: Fix/remove tools (fixes #471)
  package.json
  tools/convert.js
  tools/create-test.js
  tools/generate-identifier-regex.js
  tools/generate-test-fixture.js
  tools/list-complexity.js
  tools/sync-docs.js
  tools/update-coverage.sh
  tools/update-tests-esprima.js
  tools/update-tests.js
Labels: accepted, chore

#482 Chore: rm devdep leche (fixes #480)
  package.json
  tests/lib/ecma-features.js
  tests/lib/ecma-version.js
  tests/lib/libraries.js
Labels: accepted, dependency

#481 Build: add node v16
  .github/workflows/ci.yml
Labels: accepted, build

#485 Chore: remove --legacy-peer-deps for Node 15
  .github/workflows/ci.yml
Labels: accepted, chore

#461 Breaking: syncing start/end with range (fixes #349)
  lib/espree.js
  tests/lib/parse.js
Labels: accepted, breaking

#487 Chore: Add tests and comments for #349
  lib/espree.js
  tests/lib/parse.js
Labels: accepted, chore

#491 Chore: fix incorrect comment
  lib/espree.js
Labels: accepted, chore

#492 Upgrade: acorn to 8.2.2 (fixes #472)
  package.json
  tests/lib/parse.js
Labels: accepted, bug, dependency
