Repository eslint/js, pull requests merged in 2022-04, with the labels that each got.

#546 build: add node v18
  .github/workflows/ci.yml
Labels: accepted, build

#545 chore: lint tool files, add editorconfig, update devDeps.
  .editorconfig
  .eslintignore
  .eslintrc.cjs
  .gitignore
  package.json
  tools/create-test.js
  tools/update-tests.js
  tools/update-version.js
Labels: chore

#547 fix: "use strict" should not trigger strict mode in es3.
  package.json
  tests/fixtures/ecma-version/3/strict/func-strict.module-result.js
  tests/fixtures/ecma-version/3/strict/func-strict.result.js
  tests/fixtures/ecma-version/3/strict/func-strict.src.js
  tests/fixtures/ecma-version/3/strict/use-strict.module-result.js
  tests/fixtures/ecma-version/3/strict/use-strict.result.js
  tests/fixtures/ecma-version/3/strict/use-strict.src.js
Labels: bug, accepted
