Repository eslint/js, pull requests merged in 2022-02, with the labels that each got.

#534 chore: switch from nyc to c8 for ESM coverage
  package.json
Labels: triage, chore

#532 fix: Derive espree.Syntax from espree.VisitorKeys
  espree.js
  lib/ast-node-types.js
  tests/lib/syntax.js
Labels: bug, accepted

#536 docs: update Build Status badge
  README.md
Labels: accepted, documentation
