Repository eslint/js, pull requests merged in 2023-03, with the labels that each got.

#562 feat: Add parser name
  espree.js
Labels: accepted, feature

#565 chore: Add `lint-staged`
  .lintstagedrc.json
  package.json
Labels: accepted, chore

#567 fix: remove useless sourcemap url (#566)
  package.json
  rollup.config.js
Labels: bug, accepted

#568 chore: upgrade eslint-visitor-keys@3.4.0
  package.json
Labels: accepted, chore
