Repository eslint/js, pull requests merged in 2024-08, with the labels that each got.

#617 chore: move to `npm-run-all2`
  packages/espree/package.json
Labels: chore

#619 fix: update links to `eslint/js` repo
  .github/ISSUE_TEMPLATE/config.yml
  packages/eslint-scope/README.md
  packages/eslint-scope/package.json
  packages/espree/README.md
  packages/espree/docs/README.md
  packages/espree/docs/index.html
  packages/espree/package.json
Labels: bug

#621 docs: update links to eslint-visitor-keys repo
  packages/eslint-scope/README.md
  packages/eslint-visitor-keys/README.md
  packages/espree/README.md
  packages/espree/docs/README.md
Labels: documentation
