Repository eslint/js, pull requests merged in 2024-09, with the labels that each got.

#627 chore: Add pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#631 fix: Update dependencies to avoid build failure
  .github/workflows/ci.yml
  package.json
  packages/eslint-scope/package.json
  packages/eslint-visitor-keys/package.json
  packages/eslint-visitor-keys/tests/lib/get-keys-from-ts.js
  packages/eslint-visitor-keys/tools/backward-compatible-keys.js
  packages/eslint-visitor-keys/tools/build-keys-from-ts.js
  packages/eslint-visitor-keys/tools/get-keys-from-ts.js
  packages/eslint-visitor-keys/tsconfig.json
  packages/espree/package.json
Labels: bug, accepted

#633 fix: Remove node:assert dependency
  packages/eslint-scope/lib/assert.js
  packages/eslint-scope/lib/index.js
  packages/eslint-scope/lib/referencer.js
  packages/eslint-scope/lib/scope-manager.js
  packages/eslint-scope/lib/scope.js
Labels: bug

#634 chore: remove assert from rollup external array
  packages/eslint-scope/rollup.config.js
Labels: chore
