Repository eslint/js, pull requests merged in 2024-10, with the labels that each got.

#636 docs: Use prerendered sponsors for README
  README.md
  package.json
  packages/eslint-scope/README.md
  packages/eslint-visitor-keys/README.md
  packages/espree/README.md
  tools/update-readme.js
Labels: accepted, documentation

#637 chore: Remove unnecessary IIFE in update-readme
  tools/update-readme.js
Labels: chore

#638 ci: add Node.js v23
  .github/workflows/ci.yml
Labels: build

#639 feat: add support for Import Attributes and RegExp Modifiers
  packages/eslint-scope/tests/import-attributes.js
  packages/eslint-visitor-keys/lib/visitor-keys.js
  packages/espree/package.json
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-dupe-key.module-result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-dupe-key.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-dupe-key.src.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-dynamic-with-multiple-trailing-comma.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-dynamic-with-multiple-trailing-comma.src.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-multiple-trailing-comma.module-result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-multiple-trailing-comma.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-multiple-trailing-comma.src.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-key.module-result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-key.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-key.src.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-value.module-result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-value.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/invalid-import-attributes-with-number-value.src.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/valid-import-attributes.module-result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/valid-import-attributes.result.js
  packages/espree/tests/fixtures/ecma-version/16/import-attributes/valid-import-attributes.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-add-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-add-modifiers.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-modifiers.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-remove-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-dupe-remove-modifiers.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-empty-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-empty-modifiers.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-unknown-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/invalid-regexp-unknown-modifiers.src.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/valid-regexp-modifiers.result.js
  packages/espree/tests/fixtures/ecma-version/16/regexp-modifiers/valid-regexp-modifiers.src.js
Labels: accepted, feature, contributor pool

#641 docs: Support for Import Attributes and RegExp Modifiers
  packages/espree/docs/README.md
Labels: documentation
